plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.yniyniyni.hidevpnicon'
    compileSdk 37

    defaultConfig {
        applicationId 'dev.yniyniyni.hidevpnicon'
        minSdk 29
        targetSdk 37
        versionCode 1
        versionName '1.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:101.0.1'
    testImplementation 'junit:junit:4.13.2'
}
